spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: 'true'
    hibernate:
      ddl-auto: create-drop
    open-in-view: 'false'
  mvc:
    hiddenmethod:
      filter:
        enabled: 'true'

  sql:
    init:
      mode:always
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    password: 'root'
    username: 'root'
    url: jdbc:mysql://localhost:3306/beers?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true&serverTimezone=UTC
logging:
  level:
    org:
      hibernate:
        type:
          descriptor: TRACE
        SQL: DEBUG
      nodeValue: WARN
    blog: WARN
server:
  port: 8080
  error:
    include-message: always
